### ISSUE TITLE
Binary/Source Version Mismatch

### ISSUE THREAD

**Issue by liushuyu** [flathub/org.videolan.VLC.Plugin.fdkaac#3]
Hi there,

I was trying to install this extension in order to use the AAC encoding functionality in VLC and I found out that it didn't work. 

It turned out the version in the FlatHub was `branch 3-1.6` while the latest version here is `branch 3-18.08`.

Is this intentional or there is a problem with the build?

Thanks

**Comment by liushuyu** [comment]
Ping?

**Comment by MatMaul** [comment]
Hum indeed I tried to relaunch a build, let's see.
https://flathub.org/builds/#/builders/32/builds/4505

**Comment by liushuyu** [comment]
…… and it failed due to validation errors.

**Comment by MatMaul** [comment]
Nope it's fine it's just warnings :) It's now live, I just installed it.

**Comment by liushuyu** [comment]
Thanks, it's working now! :smiley:
